apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "YXZidHJpZm9yazpnaHBfcVUyVkVXcUhBZjEwcXlhUDA4eDBhVG9lN1gxeFZ4MVBJZXI3Cg"
        }
      }
    }
type: kubernetes.io/dockerconfigjson
