# This is for demo purposes only. Do NOT use hardcoded credentials in production!
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "avbtrifork",
          "password": "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",
          "auth": "YXZidHJpZm9yazpnaHBfY0VJSjA5d1BoODVobmFVdDZDMURXUTFCTFl3Y05DMFkzeFBr"
        }
      }
    }
