# This is for demo purposes only. Do NOT use hardcoded credentials in production!
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "avbtrifork",
          "password": "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",
          "email": "avb@trifork.com",
          "auth": "YXZidHJpZm9yazpnaHBfZWlZekNUa01JbHVLUUlnbVFQTDVvTnQxdGJQNHZDMVc4OUZR"
        }
      }
    }
