# This is for demo purposes only. Do NOT use hardcoded credentials in production!
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "YXZidHJpZm9yazpnaHBfRlJJMXNrUGJMblVZdnlyMWNYbXlIcThJNkQwV3lZMk16MTU0"
        }
      }
    }

