apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-demo-content-v4
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>Dev Really Changed Somethingss </title>
    </head>
    <body>

    <h1>Dev</h1>

    </body>
    </html>
