apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "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"
        }
      }
    }
type: kubernetes.io/dockerconfigjson
